use_frameworks!

platform :ios, '8.0'

target 'wjc_Example' do
  pod 'wjc', :path => '../'

  target 'wjc_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'Specta'
    pod 'Expecta'
  end
end
